### PR TITLE
Improve Actions CI success rate at 1st attempt

### PR DESCRIPTION
**Pull request by juanep97**

### CODE REVIEW

**Comment by juanep97** [comment]
I think we are going to need to go on the self-hosted runner route @morcuended. Atm, test passing depend a lot on random factors... and on multiples attempt. Not really continuous integration if you have to stop and check the test pass at three times at 30min intervals. I reopen #19 .

**Comment by morcuended** [comment]
Sure, let's explore that path.

**Comment by juanep97** [comment]
It seems that running one test at a time with -s (single thread in httpdirfs) works. So it might be a limitation of the astrometry index files archive.

**Comment by juanep97** [comment]
Okey, I would say merge since it seems it improves the success rate at first attempt. Checks take more time with `httpdirfs -s` and `max-parallel: 1`, but it's better than failing almost every time. The final solution is probably a self-hosted runner.

**Pull request merged**
