### PR TITLE
Update installation instructions and update citation

### PR DESCRIPTION
**Pull request by morcuended**
After hosting iop4 in PyPI, iop4 installation instructions can be eased.
Also updated citation of Zenodo reference.

### CODE REVIEW

**Comment by juanep97** [comment]
Maybe we should directly use the zenodo doi for last version, [10.5281/zenodo.10222722](https://zenodo.org/doi/10.5281/zenodo.10222722)?

**Comment by morcuended** [comment]
> Maybe we should directly use the zenodo doi for last version, [10.5281/zenodo.10222722](https://zenodo.org/doi/10.5281/zenodo.10222722)?

That doi represents all versions that I think links to the latest version. You usually want to cite the exact version used for the reduction. Plus the peer-reviewed general paper. So I guess that we could point here to the last version with the caveat of citing the version used?

**Comment by morcuended** [comment]
Changed Zenodo link to all-version one

**Comment by juanep97** [comment]
LGTM

**Review by juanep97 — APPROVED** [review]

**Pull request merged**
