### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by juanep97**
Include reference to the published IOP4 paper.

### CODE REVIEW

**Review by morcuended — DISMISSED** [review]
I think that the paper reference should be shown at the beginning of the readme

**Comment by juanep97** [comment]
The links, you say? Feel free to modify and merge.

**Comment by morcuended** [comment]
At least mention at the beginning of the readme the publication, although later the "Cite this software" section is at the end. I'm changing it.

**Comment by morcuended** [comment]
@juanep97 any idea why the docs building is failing? Is it because of the change of test file checksum in #123? The log messages in the action are not informative on the error. Anyway, these changes in the readme have nothing to do with that so I think this can be merged.

**Comment by juanep97** [comment]
Looks like the process was killed by the runner... Let's see if it passes now, running alone.

**Comment by juanep97** [comment]
Finished now, and worked. I think the failed run coincided with some process (an automatic update) that reduced the available memory for the runners, and the host OOM killed them.

**Review by morcuended — APPROVED** [review]

**Pull request merged**
